config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'

  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/xoatheloai/:id/' =>'theloais#destroy' ,as: :xoatheloai
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get '/xoatruyen/:id/' =>'edittruyens#destroy' ,as: :xoatruyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'
  get '/xoabinhluan/:id/' =>'binhluans#destroy' ,as: :xoabinhluan
  get '/search'=>'truyens#search'
  resources :rating
  post '/ratings' => 'ratings#create'
  resources :finalrate
  get '/updaterate/:id' => 'finalrates#updaterate' ,as: :updaterate
  get '/createcolumn/:id' =>'finalrates#create',as: :createcolumn
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/finalrate.rb
class Finalrate < ApplicationRecord
	belongs_to :truyen
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :truyen
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
  belongs_to :theloai
  has_many :binhluans
  has_many :ratings
  has_one :finalrate
  def self.search(search)
     where("name_vn LIKE ?", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/edittruyens_controller.rb
class EdittruyensController < ApplicationController
	def new
    @truyen = Truyen.new
    @theloais=Theloai.all
  end
  def edit
    @theloais=Theloai.all
    @truyen = Truyen.find(params[:id])
  end
  def list
    @theloais=Theloai.all
    @truyens=Truyen.all
  end
  def create
    @truyen = Truyen.new(truyen_params)
    if @truyen.save
      redirect_to createcolumn_path(@truyen.id)
    end
  end
  def update
    @truyen = Truyen.find(params[:id])
    if @truyen.update(truyen_params)
      redirect_to '/edit'
    end
  end
	def destroy
    @truyen = Truyen.find(params[:id])
    @truyen.destroy

    redirect_to edit_path
  end
  private
  def truyen_params
    params.require(:truyen).permit(:name_vn, :name_en, :content_vn, :content_en, :image, :theloai_id,:rate)
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
  @theloais=Theloai.all
  @truyens=Truyen.order("updated_at DESC")

  # CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG view)
  @average_rate=0
  @Is_average_rate_int=true
  @count=0

end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/edittruyens_helper.rb
module EdittruyensHelper
end

app/helpers/finalrates_helper.rb
module FinalratesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/edittruyens/edit.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.css" type="text/css"> </head>

  <body class="bg-inverse">
    <div class="py-5">
      <div class="container"><p class="lead text-white">Edit truyện</p>
        <div class="row">
          <div class="col-md-12">
            <%= form_for @truyen do |f| %>
            <div class="form-group text-white"> <label>Tên tiếng Việt</label> <%= f.text_field :name_vn ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Tên tiếng Anh</label> <%= f.text_field :name_en  ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Nội dung tiếng Việt</label> <%= f.text_area :content_vn ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Nội dung tiếng Việt</label> <%= f.text_area :content_en ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>URL hình ảnh</label> <%= f.text_field :image ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Thể loại</label>
              <h5 class="text-white">điền số ứng với thể loại</h5>
              <ol>
                <% @theloais.each do |t|%>
                <li>
                  <p class="text-white"><%=t.title %></p>
                </li>
                <%end%>
              </ol>
              <br>
              <%= f.text_field :theloai_id ,class: "form-control"%> </div>
              <%= f.submit "OK",class: "btn btn-primary text-white" %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
      <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>
    </body>

    </html>

app/views/edittruyens/list.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.css" type="text/css"> </head>

<body class="bg-inverse">
  <div class="py-5">
    <div class="container">
      <p class="lead text-white">Chọn truyện muốn edit</p>
      <div class="row">
        <div class="col-md-12">
          <table class="table table-inverse table-striped table-bordered table-hover table-reflow">
            <thead>
              <tr>
                <th>#</th>
                <th>Tên</th>
              </tr>
            </thead>
            <tbody>
              <% @truyens.each do |t| %>
              <tr>
                <td><a href="<%=edittruyen_path(t)%>" class="text-white"><%= t.id %></a></td>
                <td><a href="<%=edittruyen_path(t)%>" class="text-white"><%= t.name_vn %></a></td>
              </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
  <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>
</body>

</html>

app/views/edittruyens/new.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.css" type="text/css"> </head>

  <body class="bg-inverse">
    <div class="py-5">
      <div class="container"><p class="lead text-white">Thêm truyện</p>
        <div class="row">
          <div class="col-md-12">
            <%= form_for @truyen do |f| %>
            <div class="form-group text-white"> <label>Tên tiếng Việt</label> <%= f.text_field :name_vn ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Tên tiếng Anh</label> <%= f.text_field :name_en  ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Nội dung tiếng Việt</label> <%= f.text_area :content_vn ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Nội dung tiếng Việt</label> <%= f.text_area :content_en ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>URL hình ảnh</label> <%= f.text_field :image ,class: "form-control"%> </div>
            <div class="form-group text-white"> <label>Thể loại</label>
              <h5 class="text-white">điền số ứng với thể loại</h5>
              <ol>
                <% @theloais.each do |t|%>
                <li>
                  <p class="text-white"><%=t.title %></p>
                </li>
                <%end%>
              </ol>
              <br>
              <%= f.text_field :theloai_id ,class: "form-control"%> </div>
              <%= f.submit "OK",class: "btn btn-primary text-white" %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
      <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>
    </body>

    </html>