config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'

  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/xoatheloai/:id/' =>'theloais#destroy' ,as: :xoatheloai
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get '/xoatruyen/:id/' =>'edittruyens#destroy' ,as: :xoatruyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'
  get '/xoabinhluan/:id/' =>'binhluans#destroy' ,as: :xoabinhluan
  get '/search'=>'truyens#search'
  resources :rating
  post '/ratings' => 'ratings#create'
  resources :finalrate
  get '/updaterate/:id' => 'finalrates#updaterate' ,as: :updaterate
  get '/createcolumn/:id' =>'finalrates#create',as: :createcolumn
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/finalrate.rb
class Finalrate < ApplicationRecord
	belongs_to :truyen
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :truyen
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
  belongs_to :theloai
  has_many :binhluans
  has_many :ratings
  has_one :finalrate
  def self.search(search)
     where("name_vn LIKE ?", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
  @theloais=Theloai.all
  @truyens=Truyen.order("updated_at DESC")

  # CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG view)
  @average_rate=0
  @Is_average_rate_int=true
  @count=0

end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/finalrates_helper.rb
module FinalratesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/show.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.css" type="text/css">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97841360-1', 'auto');
  ga('send', 'pageview');

  </script>
 </head>

  <body class="bg-inverse">
    <div class="py-5"><div class="container"><div class="row"><div class="col-md-12"><a href="<%=themtheloai_path%>" class="btn btn-outline-warning btn-block btn-lg" data-toggle="">Thêm thể loại</a></div></div></div></div>
    <div class="py-5"><div class="container"><div class="row"><div class="col-md-12"><a href="<%=edit_path%>" class="btn btn-outline-warning btn-block btn-lg" data-toggle="">Chỉnh sửa truyện</a></div></div></div></div>
    <div class="py-5"><div class="container"><div class="row"><div class="col-md-12"><a href="<%=uptruyen_path%>" class="btn btn-outline-warning btn-block btn-lg" data-toggle="">Thêm truyện</a></div></div></div></div>
    <!-- TABLE-->
    <div class="py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <table class="table table-inverse table-striped table-bordered table-hover table-reflow">
              <thead>
                <tr>
                    <th>id</th>
                    <th>Tên</th>
                    <th>Họ</th>
                    <th>Email</th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |t|%>
                  <tr>
                    <td><%= t.id%></td>
                    <td><%= t.first_name%></td>
                    <td><%= t.last_name%></td>
                    <td><%= t.email%></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <div class="col-md-6">
              <table class="table table-inverse table-striped table-bordered table-hover table-reflow">
                <thead>
                  <tr>
                      <th>#</th>
                      <th>Bình luận</th>
                      <th>Truyện</th>
                      <th>User</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @binhluans.each do |t|%>
                    <tr>
                      <td><%= t.id%></td>
                      <td><%= t.content%></td>
                      <td><%= t.truyen_id%></td>
                      <td><%= t.user_id%></td>
                      <td><%= link_to 'DELETE', xoabinhluan_path(t), method: :delete ,class: "btn btn-outline-secondary"%></td>
                      </tr>
                      <%end%>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
          <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>
        </body>

        </html>

app/views/admin/super.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
</head>
<body>
<div class="section">
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <ul>
              <% @users.each do |t|%>
              <li>
                <%="first name : #{t.first_name} | last name : #{t.last_name} | email : #{t.email}"%>
              </li>
              <%end%>
            </ul>
          </div>
          <div class="col-md-6">
            <ul>
              <% @binhluans.each do |t|%>
              <li>
                <%="noi dung bl : #{t.content} | thuoc truyen : #{t.truyen_id} | thuoc user : #{t.user_id}"%>
                <%= link_to 'DELETE', xoabinhluan_path(t), method: :delete ,class: "btn btn-default"%>
              </li>
              <%end%>
            </ul>
          </div>
        </div>
      </div>
    </div>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FAM-Truyện Song Ngữ</title>
  <link rel="icon" type="image/gif" href="http://www.freeiconspng.com/uploads/book-stack-icon--icon-search-engine-16.png" />
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  

  <%= yield %>
      
</html>