config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'

  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/xoatheloai/:id/' =>'theloais#destroy' ,as: :xoatheloai
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get '/xoatruyen/:id/' =>'edittruyens#destroy' ,as: :xoatruyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'
  get '/xoabinhluan/:id/' =>'binhluans#destroy' ,as: :xoabinhluan
  get '/search'=>'truyens#search'
  resources :rating
  post '/ratings' => 'ratings#create'
  resources :finalrate
  get '/updaterate/:id' => 'finalrates#updaterate' ,as: :updaterate
  get '/createcolumn/:id' =>'finalrates#create',as: :createcolumn
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/finalrate.rb
class Finalrate < ApplicationRecord
	belongs_to :truyen
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :truyen
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
  belongs_to :theloai
  has_many :binhluans
  has_many :ratings
  has_one :finalrate
  def self.search(search)
     where("name_vn LIKE ?", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @theloais=Theloai.all
    @truyenmoi=Truyen.order("updated_at DESC")
    @Is_average_rate_int=true
    @average_rate=0
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
  @theloais=Theloai.all
  @truyens=Truyen.order("updated_at DESC")

  # CODE LAY DU LIEU RATE TUNG TRUYEN ( CODE NAY DI KEM CODE TRONG view)
  @average_rate=0
  @Is_average_rate_int=true
  @count=0

end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/finalrates_helper.rb
module FinalratesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.css" type="text/css">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97841360-1', 'auto');
  ga('send', 'pageview');

  </script>
</head>

<body class="bg-inverse">
  <!-- THANH BAR-->
  <nav class="navbar navbar-expand-md bg-inverse navbar-inverse">
    <div class="container"> <a class="navbar-brand" href="<%=home_path%>">Truyện Song Ngữ</a> <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active"> <a class="nav-link" href="<%=home_path%>">Trang chủ <span class="sr-only">(current)</span></a> </li>
        <li class="nav-item"> <a class="nav-link" href="<%=new_path%>">Truyện mới</a> </li>
        <li class="nav-item"> <a class="nav-link" href="<%=all_path%>">Tất cả</a> </li>
        <li class="nav-item dropdown">
          <button class="btn btn-outline-secondary dropdown-toggle text-white" data-toggle="dropdown"> Thể loại </button>
          <div class="dropdown-menu">
            <% @theloais.each do |t|%>
            <a class="dropdown-item" href="<%= theloai_path(t) %>"><%= t.title%></a>
            <%end%>
          </div>
        </li>
      </ul>
      <%= form_tag(search_path, :method => "get", id: "search-form" ,class: "form-inline my-lg-0") do %><%= text_field_tag :search, params[:search],class: "form-control mr-sm-2" , :placeholder => "Tìm Kiếm"%><button class="btn my-2 my-sm-0 btn-outline-secondary" type="submit"><i class="fa fa-fw fa-search"></i></button> <%end%>
      <% if current_user%><a href="<%= logout_path%>" class="btn btn-default navbar-btn text-white mx-5">Đăng xuất</a>
      <li class="dropdown"><a class="btn btn-outline-secondary dropdown-toggle text-white" href="#" data-toggle="dropdown" role="button"aria-expanded="false"><img src="https://pingendo.com/assets/photos/user_placeholder.png" width="30" height="30" class="d-inline-block align-top mx-1" alt=""></a>
        <div class="dropdown-menu">
          <a class="dropdown-item text-uppercase" href="" ><%="#{current_user.first_name} #{current_user.last_name}"%></a>
        </div>
      </li>
      <%else%><a href="<%=login_path%>" class="btn btn-default navbar-btn text-white mx-5">Đăng nhập</a><%end%>
    </div>
  </div>
</nav>
<div class="section text-center">
  <div class="container">
    <div class="row"> <i class="fa fa-3x fa-fw fa-book text-white"></i>
      <h1 class="text-white">Truyện Song Ngữ Anh-Việt</h1>
    </div>
    <hr class="bg-faded">
  </div>
</div>
<div class="py-5  section">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1 class="text-white">Truyện song ngữ</h1>
        <p class="lead text-white">Đọc sách ^^!<br><br>Đọc sách mang lại cho ta rất nhiều tri thức mới, đưa ta đến với văn hóa từ các nơi trên thế giới, nhưng kiến thức uyên sâu mà ông cha ta đã để lại, nhưng vẻ đẹp kì vĩ của thiên nhiên, ...<br><br>Không chỉ mang đến lợi ích
          từ việc đọc sách, việc đọc sách song ngữ có thể giúp trau dồi thêm khả năng về ngôn ngữ của nước ngoài, lại mở rộng hơn về văn hóa và lỗi sống của họ.&nbsp;<br><br>Với mục đích đó, những mẩu truyện được sưu tầm giúp chúng ta có thể vừa tiếp
          thu thêm kiến thức, vừa trau dồi vốn từ vựng và ngữ pháp, lại vừa có thể thư giãn sau một ngày làm việc căng thẳng&nbsp;<br><br>Nào chúng ta cùng đọc sách nào!&nbsp; &nbsp;&nbsp;</p>
        </div>
        <div class="col-md-6"><img src="https://usatcollege.files.wordpress.com/2014/09/139786707.jpg" class="img-fluid"><br><br>
          <ol>
            <% @theloais.each do |t| %>
            <li><a href="<%= theloai_path(t) %>" class="text-white"><%= t.title%></a></li>
            <%end%>
          </ol>
        </div>
      </div>
      <hr class="bg-faded">
      <p class="text-white">Mới cập nhật</p>
    </div>
  </div>
  <div class="">
    <div class="container  w-100">
      <div class="row">
        <div class="col-md-12">
          <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <div class="container">
                  <div class="row">
                    <% @truyenmoi[0,4].each do |t| %>
                    <div class="col-md-3">
                      <a href="<%= truyen_path(t)%>" style="opacity: 1;" title="<%= truncate t.content_vn, length: 300 %>"><img src="<%= t.image%>" class="center-block img-fluid d-block"></a>
                      <h2><a href="<%=truyen_path(t)%>" title="<%= truncate t.content_vn, length: 300 %>" class="text-white"><%= truncate t.name_vn, length: 30 %></a></h2>
                      <p class="lead text-white"><%= truncate t.content_vn, length: 40 %></p>
                      <p class="text-white"><%="#{time_ago_in_words(t.updated_at.in_time_zone(7))} ago"%></p>
                    </div>
                    <%end%>
                  </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="container">
                  <div class="row">
                    <% @truyenmoi[4,4].each do |t| %>
                    <div class="col-md-3">
                      <a href="<%= truyen_path(t)%>" style="opacity: 1;" title="<%= truncate t.content_vn, length: 300 %>"><img src="<%= t.image%>" class="center-block img-fluid d-block"></a>
                      <h2><a href="<%=truyen_path(t)%>" title="<%= truncate t.content_vn, length: 300 %>" class="text-white"><%= truncate t.name_vn, length: 30 %></a></h2>
                      <p class="lead text-white"><%= truncate t.content_vn, length: 40 %></p>
                      <p class="text-white"><%="#{time_ago_in_words(t.updated_at.in_time_zone(7))} ago"%></p>
                    </div>
                    <%end%>
                  </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="container">
                  <div class="row">
                    <% @truyenmoi[8,4].each do |t| %>
                    <div class="col-md-3">
                      <a href="<%= truyen_path(t)%>" style="opacity: 1;" title="<%= truncate t.content_vn, length: 300 %>"><img src="<%= t.image%>" class="center-block img-fluid d-block"></a>
                      <h2><a href="<%=truyen_path(t)%>" title="<%= truncate t.content_vn, length: 300 %>" class="text-white"><%= truncate t.name_vn, length: 30 %></a></h2>
                      <p class="lead text-white"><%= truncate t.content_vn, length: 40 %></p>
                      <p class="text-white"><%="#{time_ago_in_words(t.updated_at.in_time_zone(7))} ago"%></p>
                    </div>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="section text-center"><div class="container"><hr class="bg-faded"></div></div>

  <div class="text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-white">FAM</h1>
          <p class="text-white"> We are a group of University of Engineering and Technology </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <div class="row">
            <div class="col-md-4"><img src="https://pingendo.com/assets/photos/user_placeholder.png" class="center-block rounded-circle img-fluid my-3"></div>
            <div class="col-md-8 my-4">
              <h5 class="text-white">Ngô Hải Yến </h5>
              <p class="text-white"> K60-CD </p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="row">
            <div class="col-md-4"><img src="https://pingendo.com/assets/photos/user_placeholder.png" class="center-block rounded-circle img-fluid my-3"></div>
            <div class="col-md-8 my-4">
              <h5 class="text-white">Bùi Diệu Linh </h5>
              <p class="text-white">
                K60-CB
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="row">
            <div class="col-md-4"><img src="https://pingendo.com/assets/photos/user_placeholder.png" class="center-block rounded-circle img-fluid my-3"></div>
            <div class="col-md-8 my-4">
              <h5 class="text-white">Đinh Khắc Quý </h5>
              <p class="text-white">
                K60-CAC
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="row">
            <div class="col-md-4"><img src="https://pingendo.com/assets/photos/user_placeholder.png" class="center-block rounded-circle img-fluid my-3"></div>
            <div class="col-md-8 my-4">
              <h5 class="text-white">Vũ Hoàng Long</h5>
              <p class="text-white">
                K60-CAC
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
  <script src="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-alpha.6.min.js"></script>
</body>

</html>